export const expenseSubCategories = {
  Food: {
    Soups: [
      'Spiced Pumpkin Soup',
      'Lentil Vegetable Stew',
      'Basil Tomato Soup',
    ],
    'Healthy Snacks': [
      'Coconut Chips',
      'Mango Chia Pudding',
      'Organic Cereal Bars',
      'Nutty Trail Mix',
      'Organic Brown Rice Cakes',
      'Fruit and Nut Energy Bites',
      'Rice Cakes',
      'Coconut Granola',
      'Veggie Chips Variety Pack',
      'Fruit and Nut Bars',
      'Almond Joy Munch Bars',
      'Baked Potato Chips',
      'Rainbow Veggie Chips',
    ],
    'Nuts and Seeds': ['Honey Roasted Peanuts', 'Pumpkin Seeds'],
    Cheese: [
      'Cheddar Cheese Slices',
      'Sliced Provolone Cheese',
      'Greek Feta Cheese',
      'Pepper Jack Cheese Slices',
    ],
    Yogurt: ['Greek Yogurt'],
    Juice: [
      'Apple Juice',
      'Cranberry Juice',
      'Fruit Medley Juice',
      'Raspberry Limeade',
    ],
    Tea: [
      'Matcha Green Tea Powder',
      'Peach Green Tea',
      'Green Tea Matcha Powder',
    ],
    Vegetables: ['Spaghetti Squash', 'Organic Sweet Potatoes'],
    Breads: [
      'Caraway Rye Bread',
      'Sourdough Bread',
      'Artisan Bread',
      'Artisan Flatbreads',
      'Hot Dog Buns',
      'Whole Grain Hamburger Buns',
      'Whole Wheat Bread',
      'Jalapeño Cornbread',
      'French Bread',
    ],
    Meats: [
      'Ground Turkey',
      'Spicy Chicken Wings',
      'Lemon Dill Chicken Skewers',
      'Beef Stew Meat',
      'Grass Fed Beef Patties',
      'Pork Chops',
      'Tandoori Chicken Skewers',
      'Teriyaki Chicken Skewers',
    ],
    Rice: ['Herb Seasoned Rice', 'Jasmine Rice'],
    'Granola/Cereal': [
      'Cranberry Almond Granola',
      'Vanilla Almond Granola',
      'Granola Cereal',
    ],
    Seafood: [
      'Chili Lime Shrimp',
      'Lemon Garlic Shrimp',
      'Spicy Tuna Salad',
      'Garlic Butter Shrimp',
    ],
  },
  Clothing: {
    'Casual Shirts': ['Striped Long Sleeve Shirt'],
    'Dress Shirts': ['Classic Slim Fit Shirt'],
    'Outerwear - Faux Fur': ['Faux Fur Coat'],
    'Sports Apparel': ['Athletic Compression Tights'],
    'Running Shorts': ['Running Shorts'],
    'Fitness Apparel': ['Sporty Leggings'],
    Leggings: ['Faux Leather Leggings'],
    'Athletic Footwear': ['Trainers with Mesh Inserts'],
    Boots: ['High-Top Leather Boots', 'Ankle Boots'],
    'Casual Footwear': ['Comfort Flats'],
    'Evening Wear': ['Satin Slip Dress'],
    'Casual Dresses': ['Ribbed Knit Dress', 'Floral Summer Dress'],
    'Cocktail Dresses': ['Party Mini Dress'],
    Activewear: ['Golf Polo Shirt', 'Active Racerback Tank'],
    'Graphic Tees': ['Graphic Sweatshirt', 'Vintage Graphic Tee'],
    Sweaters: ['Chunky Knit Sweater'],
    'Sustainable Fashion': ['Bamboo Cotton Tank Top'],
    Shirts: ['Relaxed Fit Henley Shirt'],
    'T-Shirts': [
      'Classic White T-Shirt',
      'High-Low Hem Tee',
      'Basic V-Neck T-Shirt',
    ],
    'Tank Tops': ['Cotton Basic Tank'],
    Bottoms: [
      'Wrap Front Midi Skirt',
      'Blue Denim Jeans',
      'Cotton Sweatpants',
      'Comfortable Jogger Pants',
      'Chino Shorts',
    ],
    Trousers: ['Linen Trousers'],
    Coats: ['Puffer Winter Coat'],
    Knitwear: ['Cable Knit Cardigan'],
    Jackets: [
      'Leather Biker Jacket',
      'Trendy Bomber Jacket',
      'Luxe Velvet Blazer',
      'Two-Tone Windbreaker',
    ],
    Outerwear: ['Winter Insulated Jacket', 'Rain Jacket'],
    Hoodies: ['Graphic Hoodie'],
    Loungewear: ['Luxury Bathrobe', 'Luxury Bath Robe'],
    'Hats & Headwear': ['Winter Knit Beanie'],
    Scarves: ['Ethical Wool Scarf', 'Knitted Infinity Scarf'],
    Headwear: ['Classic Baseball Cap'],
    Bags: ['Fashionable Fanny Pack'],
    Handbags: ['Leather Crossbody Bag'],
  },
  Travel: {
    'Travel Accessories': [
      'Travel Orthopedic Pillow',
      'Compressible Packing Cubes',
      'Lightweight Travel Backpack',
      'Compressed Towel Tablets',
      'Travel Size Toiletry Bottles',
    ],
  },
  Office: {
    'Office Supplies': ['Customizable Name Plate'],
    'Office Accessories': [
      'Under Desk Footrest',
      'Leather Notebook Cover',
      'Computer Monitor Stand',
      'Sturdy Bookends',
    ],
    'Laptop Accessories': [
      'Workstation Laptop Stand',
      'Adjustable Laptop Stand',
    ],
    Furniture: ['Adjustable Height Standing Desk Converter'],
    Lighting: ['Desk Lamp with USB Port'],
    'Printers & Scanners': ['Wireless Printer'],
  },
  Pets: {
    'Pet Accessories': [
      'Pet Bed',
      'Personalized Pet ID Tags',
      'Collapsible Pet Dog Bowl',
      'Pet Food Storage Container',
      'LED Flashing Pet Collar',
    ],
    'Cat Furniture': ['Cat Tree', 'Cat Scratching Post with Toys'],
    'Grooming Supplies': [
      'Pet Grooming Glove',
      'Pet Hair Vacuum Cleaner Attachment',
      'Pet Grooming Kit',
      'Portable Pet Bathing Tool',
    ],
    'Training Supplies': ['Dog Training Whistle'],
    'Dog Accessories': ['Dog Walking Waist Pack'],
    'Pet Supplies': [
      'Pet Waterer with Filtration',
      'Pet Bed with Removable Cover',
    ],
    'Dog Toys': ['Dog Frisbee Toy'],
    'Travel Accessories': ['Pet Carrier', 'Pet Travel Carrier'],
    'Cat Care': ['Self-Cleaning Cat Litter Box'],
    'Pet Hydration Supplies': ['Pet Water Bottle'],
  },
  Home: {
    'Home Fragrance & Accessories': [
      'Natural Soy Candles',
      'Electric Wax Warmer',
      'Scented Candle Set',
      'Scent Diffuser Oil',
    ],
    'Home Organization': [
      'Wire Shelving Unit',
      'Suction Cup Hooks',
      'Freestanding Wine Rack',
      'Over-the-Door Shoe Organizer',
      'Set of Decorative Storage Bins',
      'Over-the-Door Hooks',
      'Bamboo Bathtub Caddy',
      'Photo Album',
      'Collapsible Storage Crates',
      'Over-The-Door Shoe Organizer',
    ],
    'Air Quality & Purification': [
      'Smart Air Purifier',
      'Bamboo Charcoal Air Purifier Bags',
    ],
    'Home Furnishings': ['Wall-Mounted Bookshelf', 'Compact Shoe Rack'],
    'Wine Storage Solutions': ['Wall-Mounted Wine Rack'],
    'Bedding & Linens': [
      'Faux Fur Throw Blanket',
      'Memory Foam Mattress Pad',
      'Decorative Throw Blanket',
      'Bamboo Memory Foam Pillow',
      'Electric Blanket',
      'Cotton Quilted Throw Blanket',
      'Fleece Throw Blanket',
      'Memory Foam Mattress Topper',
    ],
    'Lighting & Lamps': [
      'Multicolored LED Strip Lights',
      'Decorative LED Neon Sign',
      'LED Desk Lamp',
      'LED Under Cabinet Lighting',
      'Luminous Night Light',
      'LED Table Lamp',
      'LED Desk Light',
    ],
    'Decorative Wall Art & Accessories': [
      'Digital Photo Frame',
      'Wall Art',
      'Self-Adhesive Wallpaper',
      'Cushion Covers',
    ],
    'Smart Home & Security': [
      'Digital Alarm Clock',
      'Digital Thermostat',
      'Smart LED Light Strip',
    ],
    'Eco-Friendly Home Products': ['Biodegradable Trash Bags'],
    'Seasonal Home Decor': ['LED Christmas Lights'],
    'Kitchen Accessories': ['Two-Tier Fruit Basket'],
    'Home Decor': ['Magnetic Curtain Tiebacks'],
    'Cooling Appliances': ['Portable Air Conditioner'],
    'Robotic Cleaners': ['Home Cleaning Robot'],
    'Outdoor Cleaning': [
      'Pressure Washer Accessories Kit',
      'Electric Pressure Washer',
    ],
    Cameras: ['Digital Wireless Camera'],
  },
  Health: {
    'Aromatherapy & Wellness': [
      'Essential Oil Roller Bottles',
      'Essential Oils Diffuser Necklace',
    ],
    'Injury Prevention & Recovery': ['Wrist Support Brace'],
    'Oral Care & Hygiene': ['Rechargeable Electric Toothbrush'],
    'Personal Care & Grooming': ['Electric Razor', 'Smartphone UV Sanitizer'],
    'Sleep & Relaxation': ['Self-Massaging Pillow', 'Weighted Blanket'],
    'Safety & Protection': ['Breathable Face Mask Set'],
    'Wellness & Relaxation': ['Ice Pack'],
    'Nutrition & Fitness': ['Home Delivery Food Journal'],
    'Emergency Preparedness & First Aid': [
      'Deluxe First Aid Kit',
      'First Aid Kit',
    ],
    'Pain Relief & Therapy': ['Electric Heating Pad'],
    'Massage Therapy': ['Portable Massage Gun', 'Portable Massage Table'],
    'Health Devices': ['Portable Air Purifier', 'Portable UV Sterilizer'],
  },
  Toys: {
    'STEM Learning Toys': ['Educational STEM Kit'],
    'Pretend Play Toys': ["Wooden Children's Play Kitchen"],
    'Creative Toys': ["Kids' Art Easel", "Children's Art Set"],
    'Creative Arts & Crafts': ["Kids' Craft Supplies Set"],
    'Eco-Friendly Toys': ['Sustainable Wooden Toys'],
    'Board Games': ['Magnetic Chess Set', 'Puzzle Game Set'],
    'Educational Toys': [
      "Children's Educational Puzzle",
      'Customizable Name Puzzle',
    ],
    'Building Toys': ['Foam Building Blocks for Kids', "Kids' Building Blocks"],
    Puzzles: ['Wooden Puzzle Game'],
    'Remote Control Drones': ['Mini Hand Gesture Drone'],
  },
  Tools: {
    'Hand Tools': [
      'Folding Pocket Knife',
      'Repair Tool Set for Home Improvement',
    ],
    'Power Tools': [
      'Cordless Electric Screwdriver',
      'Electric Screwdriver',
      'Rechargeable Electric Screwdriver',
    ],
  },
  Car: {
    'Car Accessories': [
      'Portable Jump Starter',
      'Car Windshield Sun Shade',
      'Car Trash Can',
      'Car Sunshade',
    ],
    'Phone Accessories': ['Car Phone Mount'],
    'Car Interior Accessories': ['Car Seat Organizer'],
  },
}
