// NOTE: Removing an expenseCategory must be handled in the database by renaming the category or removing those rows
export const expenseCategories = [
  'Accessories',
  'Apps',
  'Art Supplies',
  'Audio',
  'Automotive',
  'Baby',
  'Bathroom',
  'Beauty',
  'Books',
  'Clothing',
  'Crafts',
  'Electronics',
  'Fitness',
  'Food',
  'Furniture',
  'Gaming',
  'Garden',
  'Health',
  'Home',
  'Home Appliances',
  'Home Improvement',
  'Home Security',
  'Kitchen',
  'Music',
  'Office',
  'Outdoor',
  'Pets',
  'Photography',
  'Safety',
  'Smart Home',
  'Sports',
  'Storage',
  'Tools',
  'Toys',
  'Travel',
  'Wearable Tech',
] as const

export const expenseCategoryColors = {
  Accessories: '#FF6B6B',
  Apps: '#4ECDC4',
  'Art Supplies': '#F7B801',
  Audio: '#A259FF',
  Automotive: '#FF5E3A',
  Baby: '#FFC3A0',
  Bathroom: '#00A8E8',
  Beauty: '#FF66C4',
  Books: '#6A4C93',
  Clothing: '#FF9F1C',
  Crafts: '#F15BB5',
  Electronics: '#3A86FF',
  Fitness: '#06D6A0',
  Food: '#EF476F',
  Furniture: '#8D99AE',
  Gaming: '#8338EC',
  Garden: '#70C1B3',
  Health: '#28C76F',
  Home: '#FFD166',
  'Home Appliances': '#118AB2',
  'Home Improvement': '#F3722C',
  'Home Security': '#2A9D8F',
  Kitchen: '#FFB703',
  Music: '#D81159',
  Office: '#3D348B',
  Outdoor: '#43AA8B',
  Pets: '#FFB4A2',
  Photography: '#9D4EDD',
  Safety: '#FB5607',
  'Smart Home': '#00B4D8',
  Sports: '#EF476F',
  Storage: '#6D597A',
  Tools: '#F9844A',
  Toys: '#FF7F50',
  Travel: '#1FAB89',
  'Wearable Tech': '#9A031E',
}

export const expenseDisplayMonths = [
  'Jan',
  'Feb',
  'Mar',
  'Apr',
  'May',
  'Jun',
  'Jul',
  'Aug',
  'Sep',
  'Oct',
  'Nov',
  'Dec',
]
