// NOTE: Prevents Flash of Unstyled Content (FOUC)
// https://mui.com/material-ui/integrations/nextjs/#app-router
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'

import { ApolloProviderClient, ThemeProviderClient } from '@/providers'

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={roboto.className}>
      <body>
        <ApolloProviderClient>
          <AppRouterCacheProvider>
            <ThemeProviderClient>{children}</ThemeProviderClient>
          </AppRouterCacheProvider>
        </ApolloProviderClient>
      </body>
    </html>
  )
}
